backend:
  name: 'github'
  repo: 'seanmart/resumeSite' # Branch to update (optional; defaults to master)
  branch: 'master'
publish_mode: 'editorial_workflow'
media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

collections:
  - label: 'Sections'
    name: 'sections'
    files:
      - label: 'Introduction'
        name: 'introduction'
        file: 'content/introduction.json'
        fields:
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'introduction'

          - label: 'Component'
            name: 'component'
            widget: 'hidden'
            default: 'introduction'

          - label: 'Section Name'
            name: 'sectionName'
            default: 'Introduction'
            widget: 'string'

          - label: 'Name'
            name: 'name'
            widget: 'string'

          - label: 'Position'
            name: 'position'
            widget: 'string'

          - label: 'Description'
            name: 'description'
            widget: 'text'

          - label: 'Photo'
            name: 'photo'
            widget: 'file'
            media_library:
              config:
                multiple: false

      - label: 'News'
        name: 'news'
        file: 'content/news.json'
        fields:
          - label: 'Component'
            name: 'component'
            widget: 'hidden'
            default: 'news'

          - label: 'Section Name'
            name: 'sectionName'
            default: 'Featured In:'
            widget: 'string'

          - label: 'News List'
            name: 'list'
            widget: 'list'
            fields:
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Link'
                name: 'link'
                widget: 'string'

      - label: 'Skills'
        name: 'skills'
        file: 'content/skills.json'
        fields:
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'skills'

          - label: 'Component'
            name: 'component'
            widget: 'hidden'
            default: 'skills'

          - label: 'Section Name'
            name: 'sectionName'
            default: 'Skills'
            widget: 'string'

          - label: 'Skills List'
            name: 'list'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'

              - label: 'Description'
                name: 'description'
                widget: 'text'

      - label: 'Videos'
        name: 'videos'
        file: 'content/videos.json'
        fields:
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'videos'

          - label: 'Component'
            name: 'component'
            widget: 'hidden'
            default: 'videos'

          - label: 'Section Name'
            name: 'sectionName'
            default: 'Videos'
            widget: 'string'

          - label: 'Videos List'
            name: 'list'
            widget: 'list'
            fields:
              - label: 'Link'
                name: 'link'
                widget: 'string'

      - label: 'Contact'
        name: 'contact'
        file: 'content/contact.json'
        fields:
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'contact'

          - label: 'Component'
            name: 'component'
            widget: 'hidden'
            default: 'contact'

          - label: 'Section Name'
            name: 'sectionName'
            default: 'Contact'
            widget: 'string'
