backend:
  name: 'github'
  repo: 'seanmart/resumeSite' # Branch to update (optional; defaults to master)
  branch: 'master'
publish_mode: 'editorial_workflow'
media_folder: 'static/images/uploads'

collections:
  - label: 'Sections'
    name: 'sections'
    files:
      - label: 'Introduction'
        name: 'introduction'
        file: 'content/introduction.json'
        fields:
          - label: 'Section Name'
            name: 'sectionName'
            default: 'Introduction'
            widget: 'string'
          - label: 'Name'
            name: 'name'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Photo'
            name: 'photo'
            widget: 'file'
            media_library:
              config:
                multiple: false
