backend:
  name: 'github'
  repo: 'seanmart/resumeSite' # Branch to update (optional; defaults to master)
  branch: 'master'
publish_mode: 'editorial_workflow'
media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

collections:
  - label: 'Sections'
    name: 'sections'
    files:
      - label: 'Introduction'
        name: 'introduction'
        file: 'content/introduction.json'
        fields:
          - label: 'Order'
            name: 'order'
            widget: 'hidden'
            default: 0
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'introduction'
          - label: 'Section Name'
            name: 'sectionName'
            default: 'Introduction'
            widget: 'string'
          - label: 'Name'
            name: 'name'
            widget: 'string'
          - label: 'Position'
            name: 'position'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'text'
          - label: 'Photo'
            name: 'photo'
            widget: 'file'
            media_library:
              config:
                multiple: false
      - label: 'Key Skills'
        name: 'skills'
        file: 'content/skills.json'
        fields:
          - label: 'Order'
            name: 'order'
            widget: 'hidden'
            default: 1
          - label: 'Id'
            name: 'id'
            widget: 'hidden'
            default: 'skills'
          - label: 'Section Name'
            name: 'sectionName'
            default: 'Key Skills'
            widget: 'string'
          - label: 'Skills'
            name: 'skills'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'text'
